<a href="https://colab.research.google.com/github/Revanthkola/Data_Analysis_With_Python/blob/main/DA_DAY2_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#random module is sub-package of numpy

In [ ]:
A=np.random.rand(1) #rand-Range is between 0 and 1
print(A)

[0.04946641]


In [ ]:
A=np.random.rand(8,4) #rand-Range is between 0 and 1
print(A)

[[0.23653812 0.25380158 0.0652003  0.95783538]
 [0.6418892  0.136348   0.45008937 0.51369056]
 [0.1276418  0.85382615 0.29417437 0.54740744]
 [0.12154945 0.42957969 0.84151869 0.22926916]
 [0.76719405 0.31907931 0.67145761 0.91705862]
 [0.24672913 0.42804632 0.5589726  0.46127664]
 [0.40835302 0.59253039 0.38945717 0.3576614 ]
 [0.56108786 0.17161901 0.62122744 0.65926816]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[6. 9. 1. 9.]
 [2. 3. 1. 8.]
 [3. 0. 7. 5.]
 [8. 6. 3. 5.]
 [1. 7. 4. 1.]
 [7. 4. 4. 0.]
 [1. 9. 4. 9.]
 [8. 6. 8. 7.]]


In [ ]:
A=np.arange(32).reshape(8,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
print(np.vsplit(A,4))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]]), array([[24, 25, 26, 27],
       [28, 29, 30, 31]])]


In [ ]:
np.vsplit(A,4) #split it verticle in 4

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [ ]:

np.vsplit(A,(3,7)) #split it after 3rd row and 7th row

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]),
 array([[28, 29, 30, 31]])]

In [ ]:
B=np.arange(32).reshape(4,8)
print(A)# create an array with 4 row and 8 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [ ]:
np.hsplit(B,4) #it split in horizontally

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [ ]:
np.hsplit(B,(3,5))

[array([[ 0,  1,  2],
        [ 8,  9, 10],
        [16, 17, 18],
        [24, 25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]])]

In [ ]:
np.hsplit(B,(2,4))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

**Trigonomerty**

In [ ]:
np.pi

3.141592653589793

In [ ]:
t=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(t)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(t) #convert radians into degree

array([ 45.,  60.,  90., 180.])

In [ ]:
np.deg2rad(t) #convert degree into radians

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
np.rad2deg(3.14)

179.9087476710785

In [ ]:
np.deg2rad(180)

3.141592653589793

In [ ]:
np.sin(0.785)#radians

0.706825181105366

In [ ]:
np.sin(t)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1/2)

0.5463024898437905

In [ ]:
np.tan(1)

1.5574077246549023

**Statistics**

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st) #mean

46.5

In [ ]:
np.median(st) #median

39.5

In [ ]:
np.var(st) # variance with formula

597.9166666666666

In [ ]:
np.std(st) #statistic deviation with formula

24.452334585202017

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c) #linear algebra inverse matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
c=np.arange(1,25).reshape(6,4)
print(np.argmax(c))

23


In [ ]:
c=np.floor(10*np.random.rand(24)).reshape(6,4)
print(c)

[[2. 8. 8. 0.]
 [7. 1. 6. 3.]
 [3. 7. 2. 3.]
 [0. 3. 9. 3.]
 [9. 3. 4. 6.]
 [3. 7. 0. 0.]]


In [ ]:
print(np.argmax(c)) #maximum number (index)

6


In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[1.83101955 4.86075005 7.77923002 8.91550563]
 [1.5000877  5.16399701 0.09383426 1.51412056]
 [2.4075894  7.79290305 5.17618229 2.29384893]
 [6.34368232 2.85585628 0.75587828 6.71787641]
 [1.54796845 5.26404369 0.21266799 8.51363729]
 [2.43619886 6.84082471 7.06826678 4.06476338]]


In [ ]:
np.argmax(c) #maximum number (index)

3

In [ ]:
print(np.argmax(c,axis=1)) #it checks row wise and prints maximum number index

[3 1 1 3 3 2]


In [ ]:
print(np.argmax(c,axis=0)) #it checks column wise and prints maximum number index

[3 2 0 0]


In [ ]:
print(np.argmin(c)) #minimum number (index)

6


In [ ]:
print(np.argmin(c,axis=1)) #it checks row wise and prints minimum number index

[0 2 3 2 2 0]


In [ ]:
print(np.argmin(c,axis=0)) #it checks column wise and prints minimum number index

[1 3 1 1]


**Searching**

In [ ]:
a=np.array([34,56,7,17,88,91])

In [ ]:
print(np.where(a%2==0)) # condition to print even numbers

(array([0, 1, 4]),)


In [ ]:
print(np.where(a%2!=0)) # condition to print odd numbers

(array([2, 3, 5]),)


In [ ]:
b=np.array([24,16,7,17,54,60])

In [ ]:
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [ ]:
s=np.array([6,7,8,9,10])

In [ ]:
x=np.searchsorted(s,10) #searching a number in sorted array it gives index of that number
print(x)

4


In [ ]:
name=np.array(["revanth","manohar","abdul","hemanth"])
print(np.sort(name))


['abdul' 'hemanth' 'manohar' 'revanth']


In [ ]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [ ]:
arr1=np.array([[1,2,4],[5,0,1]]) #arrays sorted
print(np.sort(arr1))

[[1 2 4]
 [0 1 5]]


**Filtering**

In [ ]:
arr2=np.array([40,4,58,44,67,78]) #filters
x=[True,False,True,False,True,True]
newarr=arr2[x]
print(newarr)

[40 58 67 78]


In [ ]:
arr=np.array([45,21,55,48,24,15,85]) #filter technique
filt=np.where(arr%2==0)
print(filt)

(array([3, 4]),)


In [ ]:
arr[filt] #filter technique

array([48, 24])

In [ ]:
arr[0],arr[1],arr[2],arr[3],arr[4],arr[5],arr[6]

(45, 21, 55, 48, 24, 15, 85)

**Iterating Through Arrays**

In [ ]:
name=np.array(["Revanth","Manohar","Abdul","Hemanth"])
initials=np.array(["K","K","M","K"])
for i,j in zip(initials,name): #zip is combine two arrays
  print(i,".",j)

NameError: name 'np' is not defined

In [ ]:
a=np.array(["Revanth","Manohar","Abdul","Hemanth"])
b=np.array(["K","K","M","K"])
c=np.array(["Sai Teja","Subramanyam","Raouf","Satya Sai"])
for i,j,k in zip(a,b,c):
  print(j,".",i," ",k)

K . Revanth   Sai Teja
K . Manohar   Subramanyam
M . Abdul   Raouf
K . Hemanth   Satya Sai


In [ ]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.multiply(a1,a2)    #multiplying two arrays
print(n)

[ 10  40  90 160 250]


In [ ]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.divide(a1,a2)  #dividing two arrays
print(n)

[10. 10. 10. 10. 10.]


In [ ]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.mod(a1,a2) #modulus of two arrays
print(n)

[0 0 0 0 0]


In [ ]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.divmod(a1,a2) #division and modulus of two arrays
print(n)

(array([10, 10, 10, 10, 10]), array([0, 0, 0, 0, 0]))


**Logarithms**

In [ ]:
a1=np.arange(1,10) #it prints the logarithms values
print(a1)
print(np.log(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
a1=np.arange(1,10) #it prints the logarithms values with base 2
print(a1)
print(np.log2(a1))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a1=np.arange(1,10) #it prints the logarithms values with base 10
print(a1)
print(np.log10(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Other Mathematical Functions **bold text**

In [ ]:
a=np.array([5,6,7,10])
x=np.cumprod(a)
print(x)

[   5   30  210 2100]


In [ ]:
a=np.array([5,6,7,10])
x=np.diff(a)
print(x)

[1 1 3]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:
a=np.array([5,6,7,10])
x=np.cumsum(a)
print(x)

[ 5 11 18 28]


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) # reduce :-takes multiple inputs gives output
print(gc)


3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a)
print(lc)

60
