<a href="https://colab.research.google.com/github/Revanthkola/Data_Analysis_With_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [1]:
#importing
import numpy as np

In [2]:
#creating 1d array
A=np.array([2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [3]:
#creating 2d array
B=np.array([[2,3,4],[6,7,8]])
print(B)

[[2 3 4]
 [6 7 8]]


In [4]:
c=np.array([[[2,3,4],[6,7,8]],[[6,9,0],[2,3,1]]])
print(c)

[[[2 3 4]
  [6 7 8]]

 [[6 9 0]
  [2 3 1]]]


In [5]:
d=np.array([[[[2,3,4],[5,6,7],[8,9,0,]],[[6,9,0],[7,8,0],[6,7,4]]]])
print(d)

[[[[2 3 4]
   [5 6 7]
   [8 9 0]]

  [[6 9 0]
   [7 8 0]
   [6 7 4]]]]


In [6]:
print(A.ndim)
print(B.ndim)
print(c.ndim)
print(d.ndim)

1
2
3
4


In [7]:
e=np.ones((3,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
f=np.ones((2,3,2))
print(f)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [9]:
g=np.zeros((3,2))
print(g)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
h=np.eye(4)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
i=np.eye(4,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [12]:
#arrange
j=np.arange(3,31,3) #(start,stop,step)
print(j)

[ 3  6  9 12 15 18 21 24 27 30]


In [13]:
k=np.arange(4,41,4).reshape(5,2)
print(k)

[[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]


In [14]:
l=np.arange(5,1001,5)
print(l)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [15]:
m=np.linspace(12,24,10)
print(m)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [16]:
n=np.linspace(15,3,10)
print(n)

[15.         13.66666667 12.33333333 11.          9.66666667  8.33333333
  7.          5.66666667  4.33333333  3.        ]


In [17]:
o=np.arange(1,7).reshape(2,3)
print(o)
p=np.arange(9,15).reshape(2,3)
print(p)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [18]:
print(o+p)

[[10 12 14]
 [16 18 20]]


In [19]:
q=np.sum((o,p))
print(q)

90


In [20]:
r=np.sum((o,p),axis=0)
print(r)

[[10 12 14]
 [16 18 20]]


In [21]:
r=np.sum((o,p),axis=2)
print(r)

[[ 6 15]
 [30 39]]


In [22]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [23]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=1))

[[4. 4.]
 [4. 4.]]


In [24]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a*b)

[[2 0]
 [0 4]]


In [25]:
print(a@b)

[[5 4]
 [3 4]]


In [26]:
b=np.array([25,289,361,81])
for i in b:
  print(np.sqrt(i),"square is",i)

5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81


In [27]:
a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b))) #columns
print("\n")
print(np.hstack((a,b))) #rows

[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]


In [28]:
c=np.arange(30).reshape(2,3,5)
print(c)
print("\n")
print(np.dstack(c))
#number of rows becomes number of groups
#columns become rows
#group becomes columns

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [29]:
#random module is sub-package of numpy
A=np.random.rand(1) #rand-Range is between 0 and 1
print(A)

[0.87416837]


In [30]:
A=np.random.rand(8,4) #rand-Range is between 0 and 1
print(A)

[[0.33714634 0.78392276 0.4151975  0.33113381]
 [0.45374282 0.99257917 0.57146998 0.2551558 ]
 [0.27930362 0.95016447 0.49106685 0.63765057]
 [0.44483533 0.41712231 0.8526195  0.08297837]
 [0.154479   0.1460086  0.11563943 0.41502645]
 [0.00368926 0.79531468 0.17253339 0.99678739]
 [0.48555015 0.68914615 0.80507412 0.02690697]
 [0.11036491 0.70779953 0.64105755 0.64461276]]


In [31]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[5. 1. 5. 4.]
 [5. 7. 9. 8.]
 [0. 3. 4. 6.]
 [5. 6. 2. 7.]
 [6. 3. 2. 9.]
 [5. 7. 2. 1.]
 [1. 4. 5. 2.]
 [9. 2. 7. 6.]]


In [32]:
A=np.arange(32).reshape(8,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [33]:
print(np.vsplit(A,4))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]]), array([[24, 25, 26, 27],
       [28, 29, 30, 31]])]


In [34]:
np.vsplit(A,4) #split it verticle in 4

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [35]:

np.vsplit(A,(3,7)) #split it after 3rd row and 7th row

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]),
 array([[28, 29, 30, 31]])]

In [36]:
B=np.arange(32).reshape(4,8)
print(A)# create an array with 4 row and 8 columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [37]:
np.hsplit(B,4) #it split in horizontally

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [38]:
np.hsplit(B,(3,5))

[array([[ 0,  1,  2],
        [ 8,  9, 10],
        [16, 17, 18],
        [24, 25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31]])]

In [39]:
np.hsplit(B,(2,4))

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

**Trignometry**

In [40]:
np.pi

3.141592653589793

In [41]:
t=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(t)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [42]:
np.rad2deg(t) #convert radians into degree

array([ 45.,  60.,  90., 180.])

In [43]:
np.deg2rad(t) #convert degree into radians

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [44]:
np.rad2deg(3.14)

179.9087476710785

In [45]:
np.deg2rad(180)

3.141592653589793

In [46]:
np.sin(0.785)#radians

0.706825181105366

In [47]:
np.sin(t)

array([7.07106781e-01, 8.66025404e-01, 1.00000000e+00, 1.22464680e-16])

In [48]:
np.cos(1)

0.5403023058681398

In [49]:
np.tan(1/2)

0.5463024898437905

In [50]:
np.tan(1)

1.5574077246549023

**Statistics**

In [51]:
st=np.array([23,45,67,89,21,34])

In [52]:
np.mean(st) #mean

46.5

In [53]:
np.median(st) #median

39.5

In [54]:
np.var(st) # variance with formula

597.9166666666666

In [55]:
np.std(st) #statistic deviation with formula

24.452334585202017

In [56]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [57]:
np.linalg.inv(c) #linear algebra inverse matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [58]:
c=np.arange(1,25).reshape(6,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [59]:
c=np.arange(1,25).reshape(6,4)
print(np.argmax(c))

23


In [60]:
c=np.floor(10*np.random.rand(24)).reshape(6,4)
print(c)

[[8. 6. 1. 1.]
 [5. 1. 8. 7.]
 [0. 9. 6. 3.]
 [2. 2. 1. 3.]
 [7. 6. 0. 7.]
 [0. 3. 1. 8.]]


In [61]:
print(np.argmax(c)) #maximum number (index)

9


In [62]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[3.40774488 7.44056124 1.69555362 1.1375867 ]
 [8.02413556 1.8795643  0.47436277 9.23922557]
 [9.22167972 0.94100946 4.27538535 9.63189725]
 [1.97003077 7.6495938  1.45592682 1.77081993]
 [0.82898785 0.53567509 1.75869134 5.71729362]
 [9.44821946 5.29587549 8.37067608 0.47606291]]


In [63]:
np.argmax(c) #maximum number (index)

11

In [64]:
print(np.argmax(c,axis=1)) #it checks row wise and prints maximum number index

[1 3 3 1 3 0]


In [65]:
print(np.argmax(c,axis=0)) #it checks column wise and prints maximum number index

[5 3 5 2]


In [66]:
print(np.argmin(c)) #minimum number (index)

6


In [67]:
print(np.argmin(c,axis=1)) #it checks row wise and prints minimum number index

[3 2 1 2 1 3]


In [68]:
print(np.argmin(c,axis=0)) #it checks column wise and prints minimum number index

[4 4 1 5]


**Searching**

In [69]:
a=np.array([34,56,7,17,88,91])

In [70]:
print(np.where(a%2==0)) # condition to print even numbers

(array([0, 1, 4]),)


In [71]:
print(np.where(a%2!=0)) # condition to print odd numbers

(array([2, 3, 5]),)


In [72]:
b=np.array([24,16,7,17,54,60])

In [73]:
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [74]:
s=np.array([6,7,8,9,10])

In [75]:
x=np.searchsorted(s,10) #searching a number in sorted array it gives index of that number
print(x)

4


In [76]:
name=np.array(["revanth","manohar","abdul","hemanth"])
print(np.sort(name))


['abdul' 'hemanth' 'manohar' 'revanth']


In [77]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [78]:
arr1=np.array([[1,2,4],[5,0,1]]) #arrays sorted
print(np.sort(arr1))

[[1 2 4]
 [0 1 5]]


**Flitering**

In [79]:
arr2=np.array([40,4,58,44,67,78]) #filters
x=[True,False,True,False,True,True]
newarr=arr2[x]
print(newarr)

[40 58 67 78]


In [80]:
arr=np.array([45,21,55,48,24,15,85]) #filter technique
filt=np.where(arr%2==0)
print(filt)

(array([3, 4]),)


In [81]:
arr[filt] #filter technique

array([48, 24])

In [82]:
arr[0],arr[1],arr[2],arr[3],arr[4],arr[5],arr[6]

(45, 21, 55, 48, 24, 15, 85)

**Iterating Through Arrays**

In [83]:
name=np.array(["Revanth","Manohar","Abdul","Hemanth"])
initials=np.array(["K","K","M","K"])
for i,j in zip(initials,name): #zip is combine two arrays
  print(i,".",j)

K . Revanth
K . Manohar
M . Abdul
K . Hemanth


In [84]:
a=np.array(["Revanth","Manohar","Abdul","Hemanth"])
b=np.array(["K","K","M","K"])
c=np.array(["Sai Teja","Subramanyam","Raouf","Satya Sai"])
for i,j,k in zip(a,b,c):
  print(j,".",i," ",k)

K . Revanth   Sai Teja
K . Manohar   Subramanyam
M . Abdul   Raouf
K . Hemanth   Satya Sai


In [85]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.multiply(a1,a2)    #multiplying two arrays
print(n)

[ 10  40  90 160 250]


In [86]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.divide(a1,a2)  #dividing two arrays
print(n)

[10. 10. 10. 10. 10.]


In [87]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.mod(a1,a2) #modulus of two arrays
print(n)

[0 0 0 0 0]


In [88]:
a1=np.array([10,20,30,40,50])
a2=np.array([1,2,3,4,5])
n=np.divmod(a1,a2) #division and modulus of two arrays
print(n)

(array([10, 10, 10, 10, 10]), array([0, 0, 0, 0, 0]))


**Logarithms**

In [89]:
a1=np.arange(1,10) #it prints the logarithms values
print(a1)
print(np.log(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [90]:
a1=np.arange(1,10) #it prints the logarithms values with base 2
print(a1)
print(np.log2(a1))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [91]:
a1=np.arange(1,10) #it prints the logarithms values with base 10
print(a1)
print(np.log10(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


**Other Mathematical Functions**

In [92]:
a=np.array([5,6,7,10])
x=np.cumprod(a)
print(x)

[   5   30  210 2100]


In [93]:
a=np.array([5,6,7,10])
x=np.diff(a)
print(x)

[1 1 3]


In [94]:
num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [95]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [96]:
a=np.array([5,6,7,10])
x=np.cumsum(a)
print(x)

[ 5 11 18 28]


In [97]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a) # reduce :-takes multiple inputs gives output
print(gc)


3


In [98]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a)
print(lc)

60
